server {
    server_name ats.astro-buddy.in;
    client_max_body_size 2m;

    location / {
        proxy_pass http://127.0.0.1:8089;
        proxy_set_header Host $host;
        proxy_read_timeout 60s;
    }

    # optional: dashboard/logs ko sirf apne IP se kholne do
    # location ~ ^/(dashboard|logs|stats) {
    #     allow YOUR.OFFICE.IP.HERE;
    #     deny all;
    #     proxy_pass http://127.0.0.1:8089;
    # }
}
